model:
  test: 
    value: false
    description: "activates test mode for agent evaluation"

  agent_name: 
    value: ${now:%Y%m%d}_sac_gnn
    description: "Agent name for training or evaluation (default: today's date + '_sac_gnn')"

  pretrained_agent: 
    value: ""
    description: "Pretrained agent for fine-tuning (default: '')"

  cplexpath: 
    value: "/opt/ibm/ILOG/CPLEX_Studio2211/opl/bin/x86-64_linux/"
    description: "defines directory of the CPLEX installation"

  directory: 
    value: "saved_files"
    description: "defines directory where to save files"

  max_episodes: 
    value: 16000
    description: "number of episodes to train agent (default: 16k)"

  max_steps: 
    value: 120
    description: "number of steps per episode (default: T=120)"

  no_cuda: 
    value: true
    description: "disables CUDA training"

  batch_size: 
    value: 100
    description: "defines batch size"

  p_lr: 
    value: 1e-3
    description: "define policy learning rate"

  q_lr: 
    value: 1e-3
    description: "defines q-value learning rate"

  hidden_size: 
    value: 256
    description: "defines hidden units in the MLP layers"

  clip: 
    value: 500
    description: "clip value for gradient clipping (default: 500)"

  checkpoint_path: 
    value: "SAC"
    description: "path, where to save model checkpoints"

  city: 
    value: "nyc_brooklyn"
    description: "defines city to train on"
